config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/help", to: "static_pages#help"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: %i(create show)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save {email.downcase!}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  validates :name, presence: true,
            length: {maximum: Settings.user.name.max_length}
  validates :email, presence: true,
            length: {maximum: Settings.user.mail.max_length},
            format: {with: VALID_EMAIL_REGEX}, uniqueness: true
  validates :password, presence: true,
            length: {minimum: Settings.user.password.min_length}
  has_secure_password

  class << self
    # Returns the hash digest of the given string.
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false unless remember_digest
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by email: params[:session][:email].downcase
    if @user&.authenticate params[:session][:password]
      # Log the user in and redirect to the user's show page.
      log_in @user
      params[:session][:remember_me] == "1" ? remember(@user) : forget(@user)
      redirect_to @user
    else
      # Create an error message
      flash.now[:danger] = t("password_invalid")
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def edit; end

  def show
    return if @user = User.find_by(id: params[:id])
    flash[:warning] = t "not_find_account"
    redirect_to signup_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = t "message_login"
      redirect_to @user
    else
      render :new
    end
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def destroy
    user = User.find_by(id: params[:id])
    if user&.destroy
      flash[:success] = "User deleted"
    else
      flash[:danger] = "Delete fail!"
    end
    redirect_to users_url
  end

  private

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  # Before filters
  # Confirms a logged-in user.
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  #Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title page_title
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.blank?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in user
    session[:user_id] = user.id
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    current_user.present?
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

    # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for (user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end

  # def check_permit_delete user
  #   return unless current_user.admin? && !current_user?(user)
  #
  #   link_to t("delete_user.title_delete"),
  #           user, method: :delete, data: {confirm: t("delete_user.u_sure")}
  # end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("sample_app.sample_app_up_case"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), root_path %></li>
        <li><%= link_to t("help"), help_path %></li>
        <li><%= link_to t("about"), about_path %></li>
        <li><%= link_to t("login"), login_path %></li>
        <li><%= link_to t("sign_up"), signup_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("users"), current_user %></li>
          <li class="dropdown">
            <%= link_to root_path, id: "setupdrop", data:{toggle: "dropdown"}, class: "dropdown-toggle" do %>
              <%= t("account") %>
              <b class="caret"></b>
                 <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("profile"), current_user %></li>
              <li><%= link_to t("settings"), "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<%= link_to ("english"), locale: :en %>
<%= link_to ("vietnamese"), locale: :vi %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all",
        "data-turbolinks-track": "reload" %>
  <%= javascript_pack_tag "application",
        "data-turbolinks-track": "reload" %>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
     	<%= t("the_form_contains") %>
      <%= t(:error, count: @user.errors.count) %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1><%= t "about" %></h1>
<p>
  <%= link_to t("about_text_0"), "https://www.railstutorial.org/" %>
  <em><%= t("about_text_1") %></em>,
  <%= t("about_text_2") %>
  <%= link_to t("about_text_4_link0"), "https://www.learnenough.com/" %>
  <%= t("about_text_3") %>, <%= t("about_text_4") %>
  <%= link_to t("about_text_4_link"), "https://www.railstutorial.org/book" %>
  <%= t("and") %>
  <%= link_to t("about_text_4_link1"), "https://screencasts.railstutorial.org/" %>
  <%= t("about_text_5") %>
  <%= link_to t("about_text_5_link"), "https://rubyonrails.org/" %>
  <%= t("about_text_6") %>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1><%= t("help") %></h1>
<p>
  <%=  t("help_text_0") %>
  <%= link_to t("help_link_0"), "https://www.railstutorial.org/help"%>
  <%= t("help_text_1") %>
  <%= link_to t("help_link_1"), "https://www.railstutorial.org/book" %>
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1><%= t("sample_app.sample_app_down_case") %></h1>
<div class="center jumbotron">
<h1><%= t("home_text_2") %></h1>
<h2>
  <%= t("home_text_0")%>
  <%= link_to t("about_text_1"),"https://www.railstutorial.org/" %>
  sample application.
</h2>
<%= link_to t("sign_up_now"), "#", class: "btn btn-lg btn-primary" %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: @user %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
         data: {confirm: "You sure?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, "Save changes") %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
 <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, t("sign_up"))%>
<h1><%= t("sign_up") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render "shared/error_messages" %>
      <%= f.label :name , t("form_name") %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email , t("form_email") %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :password , t("form_passworld")%>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :password_confirmation, t("form_reppassworld") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= f.submit t("form_button"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>